[2023-05-05 01:37:43,604] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.write_orders_to_file manual__2023-05-05T01:37:39.957433+00:00 [queued]>
[2023-05-05 01:37:43,615] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.write_orders_to_file manual__2023-05-05T01:37:39.957433+00:00 [queued]>
[2023-05-05 01:37:43,616] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:37:43,617] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-05-05 01:37:43,617] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:37:43,631] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): write_orders_to_file> on 2023-05-05 01:37:39.957433+00:00
[2023-05-05 01:37:43,634] {standard_task_runner.py:52} INFO - Started process 5087 to run task
[2023-05-05 01:37:43,638] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'write_orders_to_file', 'manual__2023-05-05T01:37:39.957433+00:00', '--job-id', '123', '--raw', '--subdir', 'DAGS_FOLDER/load_from_postgres.py', '--cfg-path', '/tmp/tmpllxwbxg4', '--error-file', '/tmp/tmp7xnnt8_4']
[2023-05-05 01:37:43,640] {standard_task_runner.py:77} INFO - Job 123: Subtask write_orders_to_file
[2023-05-05 01:37:43,724] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_pipeline.write_orders_to_file manual__2023-05-05T01:37:39.957433+00:00 [running]> on host ebd7ac88a2d5
[2023-05-05 01:37:43,769] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:43,826] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:43,840] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-05 01:37:43,854] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:163 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:43,861] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_pipeline
AIRFLOW_CTX_TASK_ID=write_orders_to_file
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T01:37:39.957433+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T01:37:39.957433+00:00
[2023-05-05 01:37:43,880] {base.py:79} INFO - Using connection to: id: postgres_local. Host: host.docker.internal, Port: 5432, Schema: sample_source_db, Login: ***, Password: ***, extra: {}
[2023-05-05 01:37:43,892] {sql.py:375} INFO - Running statement: SELECT * FROM orders, parameters: None
[2023-05-05 01:37:43,895] {sql.py:384} INFO - Rows affected: 10
[2023-05-05 01:37:43,899] {python.py:175} INFO - Done. Returned value was: None
[2023-05-05 01:37:43,919] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=write_orders_to_file, execution_date=20230505T013739, start_date=20230505T013743, end_date=20230505T013743
[2023-05-05 01:37:43,973] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-05-05 01:37:44,029] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-05 01:37:44,032] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2023-05-05 01:37:44,034] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
