[2023-05-05 01:37:44,711] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.create_customer_orders_table manual__2023-05-05T01:37:39.957433+00:00 [queued]>
[2023-05-05 01:37:44,742] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.create_customer_orders_table manual__2023-05-05T01:37:39.957433+00:00 [queued]>
[2023-05-05 01:37:44,742] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:37:44,743] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-05-05 01:37:44,743] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:37:44,756] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): create_customer_orders_table> on 2023-05-05 01:37:39.957433+00:00
[2023-05-05 01:37:44,760] {standard_task_runner.py:52} INFO - Started process 5093 to run task
[2023-05-05 01:37:44,762] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'create_customer_orders_table', 'manual__2023-05-05T01:37:39.957433+00:00', '--job-id', '128', '--raw', '--subdir', 'DAGS_FOLDER/load_from_postgres.py', '--cfg-path', '/tmp/tmpkopre0cr', '--error-file', '/tmp/tmpvpn5d4cp']
[2023-05-05 01:37:44,764] {standard_task_runner.py:77} INFO - Job 128: Subtask create_customer_orders_table
[2023-05-05 01:37:44,837] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_pipeline.create_customer_orders_table manual__2023-05-05T01:37:39.957433+00:00 [running]> on host ebd7ac88a2d5
[2023-05-05 01:37:44,870] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:44,886] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:44,894] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-05 01:37:44,904] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:163 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:44,911] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_pipeline
AIRFLOW_CTX_TASK_ID=create_customer_orders_table
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T01:37:39.957433+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T01:37:39.957433+00:00
[2023-05-05 01:37:44,924] {base.py:79} INFO - Using connection to: id: postgres_local. Host: host.docker.internal, Port: 5432, Schema: sample_source_db, Login: ***, Password: ***, extra: {}
[2023-05-05 01:37:44,935] {sql.py:375} INFO - Running statement: 
    create table if not exists customer_orders as 
    SELECT
        c.customerid, firstname, lastname, email,
        orderdate, totalamount, current_timestamp as load_ts
    FROM customers c
    INNER JOIN orders o
        ON c.customerid = o.customerid
    LIMIT 0;
    , parameters: None
[2023-05-05 01:37:44,937] {postgres.py:96} INFO - NOTICE:  relation "customer_orders" already exists, skipping

[2023-05-05 01:37:44,956] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=create_customer_orders_table, execution_date=20230505T013739, start_date=20230505T013744, end_date=20230505T013744
[2023-05-05 01:37:44,974] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-05-05 01:37:45,028] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2023-05-05 01:37:45,030] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2023-05-05 01:37:45,031] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
