[2023-05-05 01:37:45,891] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.populate_customers_orders_table manual__2023-05-05T01:37:39.957433+00:00 [queued]>
[2023-05-05 01:37:45,900] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: postgres_pipeline.populate_customers_orders_table manual__2023-05-05T01:37:39.957433+00:00 [queued]>
[2023-05-05 01:37:45,900] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:37:45,901] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2023-05-05 01:37:45,901] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2023-05-05 01:37:45,912] {taskinstance.py:1259} INFO - Executing <Task(PostgresOperator): populate_customers_orders_table> on 2023-05-05 01:37:39.957433+00:00
[2023-05-05 01:37:45,916] {standard_task_runner.py:52} INFO - Started process 5095 to run task
[2023-05-05 01:37:45,919] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'postgres_pipeline', 'populate_customers_orders_table', 'manual__2023-05-05T01:37:39.957433+00:00', '--job-id', '129', '--raw', '--subdir', 'DAGS_FOLDER/load_from_postgres.py', '--cfg-path', '/tmp/tmp5id2m_f0', '--error-file', '/tmp/tmpa6mek2n3']
[2023-05-05 01:37:45,920] {standard_task_runner.py:77} INFO - Job 129: Subtask populate_customers_orders_table
[2023-05-05 01:37:45,991] {logging_mixin.py:109} INFO - Running <TaskInstance: postgres_pipeline.populate_customers_orders_table manual__2023-05-05T01:37:39.957433+00:00 [running]> on host ebd7ac88a2d5
[2023-05-05 01:37:46,024] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/xcom.py:323 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:46,039] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:126 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:46,048] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:162 SAWarning: Coercing Subquery object into a select() for use in IN(); please pass a select() construct explicitly
[2023-05-05 01:37:46,058] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/renderedtifields.py:163 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2023-05-05 01:37:46,063] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=***@example.com
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=postgres_pipeline
AIRFLOW_CTX_TASK_ID=populate_customers_orders_table
AIRFLOW_CTX_EXECUTION_DATE=2023-05-05T01:37:39.957433+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-05-05T01:37:39.957433+00:00
[2023-05-05 01:37:46,079] {base.py:79} INFO - Using connection to: id: postgres_local. Host: host.docker.internal, Port: 5432, Schema: sample_source_db, Login: ***, Password: ***, extra: {}
[2023-05-05 01:37:46,090] {sql.py:375} INFO - Running statement: 
    INSERT INTO customer_orders (customerid, firstname, lastname, email, orderdate, totalamount, load_ts)
    SELECT
        c.customerid, c.firstname, c.lastname, c.email,
        o.orderdate, o.totalamount, current_timestamp as load_ts
    FROM customers c
    INNER JOIN orders o
        ON c.customerid = o.customerid;
    , parameters: None
[2023-05-05 01:37:46,093] {sql.py:384} INFO - Rows affected: 10
[2023-05-05 01:37:46,113] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=postgres_pipeline, task_id=populate_customers_orders_table, execution_date=20230505T013739, start_date=20230505T013745, end_date=20230505T013746
[2023-05-05 01:37:46,130] {local_task_job.py:154} INFO - Task exited with return code 0
[2023-05-05 01:37:46,175] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-05-05 01:37:46,177] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.value() is deprecated and will be removed in a future release.  Please use Query.with_entities() in combination with Query.scalar() (deprecated since: 1.4)
[2023-05-05 01:37:46,178] {logging_mixin.py:109} WARNING - /usr/local/lib/python3.7/site-packages/***/models/dag.py:1076 SADeprecationWarning: Query.values() is deprecated and will be removed in a future release.  Please use Query.with_entities() (deprecated since: 1.4)
